---
title: "1.2. Externalities and Bargaining - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required Reading:

- [<i class="fas fa-file-pdf"></i> Coase (1960), "The Problem of Social Cost"](/readings/Coase-1960.pdf)

# Tips and Questions to Read for:

This is an extremely famous paper^[It is one of the most cited papers in Economics of the 20^th^ Century.], which almost single-handedly launched the discipline of Law and Economics^[I plan to finally teach a course in this in Spring 2021!], one of the two papers that won Coase the 1991 Economics Nobel Prize. It is also quite lengthy and detailed, weaving back and forth between theoretical examples and real world legal cases. You will have a full week to read this, but **focus on sections I, II, V, VI, VII, the last paragraph on p.27-p.29, IX, X**.

- Coase uses many examples, often involving complex legal cases. The laws and quotes of the opinions of judges is not important here. You need not remember or master them all, but understand the consistent logic behind all of them.
- This article is credited with the creation of "The Coase Theorem." What is it, according to Coase?
- What kind of studies or examinations is Coase calling for economists to do that they did not normally do before?
- How do transaction costs (Coase calls these "the cost of using the market") change or affect his model/examples?
- What is the Pigouvian approach to externalities, and what does Coase have to say about it?
- What is the decision that needs to be made, according to Coase, when attempting to resolve an externality?  

