---
title: "2.1. The State as Commitment Device - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required Reading:

- [<i class="fas fa-file-pdf"></i> Hobbes (1660), Selections from *The Leviathan*](/readings/Hobbes-1660.pdf)
- [<i class="fas fa-file-pdf"></i> Machiavelli (1532), Selections from *The Price*](/readings/Machiavelli-1532.pdf)

This class kicks off our look at Constitutional Political Economy, and we will examine this topic at several levels: 

First, if we are to chose as a group at *any* level (whether a national government, a neighborhood association, or a book club), how do we *constitute* and *decide how to decide* as a group? Second, we will often look at a particular group/institution, the Nation-State, and ask what is its origin and nature. What gives the State the authority to coerce individuals? How should we empower it, and how should we constrain it?

We begin with a deep dive to a major point of departure in the Western liberal political philosophy canon. Thomas Hobbes is often invoked as the first explicit originator of the a **social contract** theory of the State. Writing during the [English Civil War](https://en.wikipedia.org/wiki/English_Civil_War) - the ultimate result of which would set the Western world on a path towards liberal democracy, constitutional republics, and the industrial revolution - Hobbes is famous for his bleak view of the [state of nature](https://en.wikipedia.org/wiki/State_of_nature) (a hypothetical society without government). He is often noted as a supporter of a strong State, whom he saw as an absolute monarch, as the solution to this problem. Hobbes is often written off quickly in political philosophy, as a predecessor to the more celebrated [John Locke](https://en.wikipedia.org/wiki/John_Locke), the clear inspiration fo the U.S. Declaration of Independence and many modern ideas. However, Hobbes provides both deep analytical insight to the nature of the problem (which can be recast in modern game theory terms), as well as a clear break from Ancient political philosophy. We will read selections from Hobbes' famous 1651 book, *Leviathan*. 

Additionally, we will read selections from equally (in)famous Niccolo Machiavelli's *The Prince.* Like Hobbes, Machiavelli has been unduly given a grim reputation, in this case, for his gritty and pragmatic view of the art politics and rule, sapping out the romance and idealism of lofty goals for perfecting humanity.

# Recommended Reading:

- [<i class="fab fa-wikipedia-w"></i> Wikipedia: "The Liberty of Ancients Compared with that of Moderns"](https://en.wikipedia.org/wiki/The_Liberty_of_Ancients_Compared_with_that_of_Moderns)

To give you some guidance in just how important Hobbes and Machiavelli are for actually *understanding* politics, I strongly suggest you skim the Wikipedia entry for Benjamin Constant's famous speech, "The Liberty of Ancients Compared with that of Moderns" (which is otherwise too long to ask you to read).

# Tips and Questions to Read for:

With these readings, we want to focus on two key ideas:

1. Politics as a series of practical solutions for autonomous people to live their own individual lives in peace and cooperation, rather than an ideal art of perfecting society.

2. Politics as rules or constraints that allow coordination and the solving of social problems.

So here are some questions to ask:

- What does Hobbes have to say about an "ultimate good" or "ultimate goal" for humanity?

- Is Hobbes a subjectivist in terms of value and human choice?

- What's the problem with everyone having equal power and limitations?

- When is it in an individual's interest to limit themselves?

- What is the origin of the State or Commonwealth?

- How would you consider Hobbes' analysis in terms of game theory? A prisoners' dilemma? A stag hunt?

- What does Machiavelli think about assessing a ruler according to the ruler's *virtue*?

- According to Machiavelli, how have older writers "imagined republics and principalities that have never really existed at all"?

- According to Machiavelli, famously, is it better for a ruler to be loved or feared, and why? How might this be strategically wise?

- What is the role of reputation in a ruler?