---
title: "2.3. The Optimal Decision Rule - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required Reading:

- <i class="fas fas fa-book"></i> Buchanan and Tullock (1962), *The Calculus of Consent*, Chs. 3,5,6

After we've digested some political philosophy (with a dose of game theory), it's time for a more "rigorous" model of choosing as a group. How should we decide how to decide?

We read the key chapters of Buchanan and Tullock's classic 1962 *Calculus of Consent*, which (mostly) launched the field of public choice as the economic analysis of politics. Buchanan won the Nobel Prize in Economics in 1986 for his contributions to this field. 

# Tips and Questions to Read for:

- "When will a society composed of free and rational utility-maximizing individuals choose to undertake action collectively rather than privately?"

- How do we determine the rules that will determine the rules by which we choose as a group?

- When/why is unanimity important? When might it make rational sense to depart from unanimity as a decision rule?

- What sorts of decisions should require more agreement, and what sorts of decisions should require less agreement?

- How is the optimal decision rule deduced?

- Should majorities decide everything? Why or why not?