---
title: "3.3. Voting III: Democracy Squared? - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

*Wednesday, February 26, 2020*

# Required Reading:

- <i class="fas fas fa-book"></i> Posner, Eric A, and E Glen Weyl (2017), *Radical Markets*, Ch. 2: "Radical Democracy"

Today we discuss one of the more interesting (and radical) proposals put forth to reform politics in a fundamental (and economic) way: to dispense with "one person one vote," allowing people to express the intensity of their preferences with (essentially) "multiple votes" that they can "buy" at an increasing cost (allowing them to make tradeoffs). Due to the typical cost function proposed for this system, this is known as **"quadratic voting"**. 

It's main proponents, legal scholar Eric Posner^[Son of famed federal judge, and law-and-economics pioneer, [Richard Posner](https://en.wikipedia.org/wiki/Richard_Posner)] and Glen Weyl, argue that it would radically improve democracy, welfare, and economic efficiency. This is one of several stimulating proposals from their book, *Radical Markets* that much of the intelligentsia has been debating over the past few years. We will discuss several others from that book this semester (and also in Industrial Organization, for some of you in that course). Aside from politics, this has also found some interest in corporate governance, and [on](https://vitalik.ca/general/2019/12/07/quadratic.html) the [blockchain](https://medium.com/eximchain/what-makes-quadratic-voting-an-effective-democratic-voting-mechanism-d7a555de8f6b).

You can certainly skim some parts in the beginning and the applications towards the end (unless you find them interesting), as this is from a book for the general public - so they need to clear a lot of ground to set this up (some of which we have covered in this course already - about public goods, externalities, strategic voting, etc). Focus on what Quadratic Voting is, how it might work, and why the authors argue it would improve our current system.

# Tips and Questions to Read for:

- What are some problems with "one person one vote"?

- What is good, bad, or objectionable about people buying, selling, or trading their votes (i.e. under our current system)?

- What realms of possibility (and problems) do we open if we start dealing with *intensities* of preferences?

- Why *quadratic*?