---
title: "3.7. The Rise of the Administrative State - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

*Wednesday, March 25, 2020*

# Readings:

- <i class="fas fa-external-link-square-alt"></i> Cooper, Charles J, 2015, ["Confronting the Administrative State,"](https://www.nationalaffairs.com/publications/detail/confronting-the-administrative-state) *National Affairs*

- <i class="fas fa-external-link-square-alt"></i> **Optional**: Wilson, Woodrow, 1887, ["The Study of Administration,"](/readings/Wilson-1887.pdf) *Political Science Quarterly*

We continue looking at bureaucracy and the role of independent agencies and regulatory commissions, and examine their tension with democracy and, some may argue, the constitution. Naturally, this conversation begins to have an ideological tinge to it, so we look at both the progressive and conservative takes on "the administrative state."

More "law" is actually created these days by independent agencies and regulatory bodies that Congress has delegated quasi legislative, executive, and judicial powers to. This raises issues about accountability, democracy, expertise, and separation of powers questions.

The Cooper article comes from National Affairs (a fairly non-Trumpian, conservative-leaning, publication) and does a good job in describing the history and evolution of the administrative state - from progressive ideas through many Supreme Court cases and Congressional statutes - as well as the debate about constitutionality and threats to liberty (his conclusion is as you might expect). Note the framing is a bit dated (2015, during the Obama Administration), but the larger points still hold.

The other article you might choose to read is an academic journal article by Woodrow Wilson, 28th President of the U.S., back when he was a professor at Princeton. He is one of the quintessential leaders and thinkers of the Progressive movement, with its focus on efficiency, scientific expertise, and rationalization of society and the economy. His well-known article separates politics from administration, setting forth many of the ideas that would define public administration as a field and build the 20th century administrative state.

# Tips and Questions to Read For:

