---
title: "3.8: Federalism"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Monday, March 30, 2020*

*Online Quarantine Lecture 3*

# Readings

See the [<i class="fas fa-book-reader"></i> Readings](/reading/3.8-reading) for today's topics. A reminder, **you are no longer required to read and email questions before class.** You still need to do the readings for the weekly discussion (see below), and if you choose to join the livestream, I recommend reading before class if you want me to answer any questions in real time.

# Class Livestream/Lecture Videos

<iframe width="560" height="315" src="https://www.youtube.com/embed/bN-i9VzmtjQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/lfrdxE1L8bo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/_jC98s4j5Jg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/w2ntprL5tjY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/qTwt5SYWzhk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

[<i class="fas fa-chalkboard-teacher"></i> Slides](/slides/3.8-slides)

# Midterm Exam

I will be emailing each of you your midterms, marked up with comments, along with your scores.

# Course Midterm Grades

As per the Registrar, all midterm grades will be posted to Self Service today (Monday March 30). I have used your midterm exam grade (20%), and your average participation score (30%) to *estimate* your midterm grade (out of 50%, not 100%). You can again estimate your final course grade (out of 100%) on the [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/410_grade_calculator/) at the top of the [Assignments page](/assignments). 

# Discussion Thread

The weekly discussion thread **will be posted** on Blackboard.^[Go to this course on Blackboard, and on the blue toolbar on the left, go to *Discussion Board.*] You will have until Sunday 11:59 PM to comment on this week's topics (based on lectures and readings), at which point I will evaluate your contribution for the weekly discussion grade. See my introductory post on the discussion board's thread for more information.