---
title: "Transition to Online Course For Spring 2020"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Overview

Welcome to online classes from quarantine!

None of us signed up for this. Some of you may be dealing hardships at home and at work, and may be juggling many problems right now. It may be awkward and difficult for you to learn at home, and for me to teach from home. We all are going to miss the human contact and sense of community from being together on campus.

Thank you to those of you who filled out my survey and gave me some helpful information. Us faculty have been training and sharing tips for the best ways to retool our courses for a sudden shift to an online semester. 

For the rest of the semester, we are going to prioritize supporting each other as human beings during this crazy period of isolation, and use simple, accessible solutions that make sense for the most people, and above all, to be flexible. Right now, you have more important needs to worry about with your families, employment, and staying sane in isolation, than schoolwork. Prioritize them. I will be flexible with times and assignments, but will try to keep some structure to the course, and as such, some deadlines. I hope you use this course as an opportunity to escape the boredom and insanity of social isolation, and to help keep interest in understanding the world around us.

In addition to email, I will make myself accessible across multiple media to ensure you get the help and support you need:

- [<i class="fas fa-video"></i> Zoom Office Hours (MW 3:30-5:00 PM)](https://zoom.us/j/458617463)
- [<i class="fab fa-slack"></i> Class Slack Channel](http://hood-public-economics.slack.com)^[Join with [this link](https://join.slack.com/t/hood-public-economics/shared_invite/zt-ctl82l2r-kYcGVUI_KDwuXJKXpXEpiQ), which expires in 7 days.]

I will host general "office hours" during my usual time, 3:30-5PM Mondays and Wednesdays, on **Zoom.** You can join in with video, audio, and/or chat, whichever you feel comfortable with. Of course, if you are not available during those times, we can schedule our own time if you prefer this method over email or Slack.

I will also be reachable on **Slack**^[Join with [this link](https://join.slack.com/t/hood-public-economics/shared_invite/zt-ctl82l2r-kYcGVUI_KDwuXJKXpXEpiQ), which expires in 7 days.], a common instant-messaging and collaboration app that many workplaces use, and I have used in some advanced courses before. I have added a link at the top of our website to our course Slack channel. Feel free to use this to ask me, and each other, questions and comments about the course and material, and to maintain contact and our shared community.

If you had never noticed, there is a [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/410_grade_calculator/) at the top of the [Assignments page](/assignments). Use this tool to calculate your final course grade and predict what grades you would need on remaining assignments to obtain a desired course grade.

# Changes to Course Structure & Assignments

Part of the unique features of this 400-level class (as opposed to our other 300-level Econ electives) is that it is seminar-like, with a focus on reading and discussion. This is to get you to grapple with challenging concepts and familiarizing yourself with what people have said about them. A lot of things we discuss are not "textbook" models with clear answers, but timeless questions that have no easy answers, and any analyst, researcher, or responsible citizen needs to grapple with on their own. Students who have taken economics electives with me in the past, and this class in particular, usually cite our classroom discussions as among their favorite part of the course, and the part that they learn the most from.

However, the abrupt transition to an online course combined with emergency circumstances means that we cannot assume everyone has equal or sufficient access to technology and time to devote to synchronous classes and discussions. 

As such, to the best of my ability, I have tried to keep some aspect of your feedback and thoughts on readings and contents of the course. I feel much less comfortable "telling you how it is" on a lot of these issues, and still invite your comments and critiques. Our "discussions" will be **asynchronous** and less frequent, allowing you to read, write, and watch my lectures at your own pace during the week.

will try to keep some sort of discussion, or your ability to react and comment, going. It will probably be more asynchronous (i.e. you can complete everything on your own schedule rather than at a fixed time) and spaced out. I will post lectures and require you to comment on some ideas or readings (perhaps a short paragraph). 

Fortunately, much of our class is already accessible online, and most assignments and lectures need only minimal changes. The following will be updated on the [Syllabus page (and PDF)](/syllabus): 

1. The **midterm and final exams** remain take home essays that you will email to me. There are no changes to be made here. See more instructions on the midterm below.

2. All **"class meetings"** will be **asynchronous**. Videos of my lectures will be hosted via Youtube (unlisted) and posted on the <i class="fas fa-info-circle"></i> **Class** pages on this website (along with the regular slides). You can watch them at your own pace, on your own time. I *will*, however, be recording my lectures *live* via *Zoom*, during our usual class meeting times:

- [<i class="fas fa-video"></i> Zoom Live Class Meetings (Mon/Wed 2:00 - 3:15 PM)](https://zoom.us/j/929467864)

> The recordings will be posted later in the day on Youtube and on the class pages. **You are not required to attend live**. You *can*, and may want to, join in live on Zoom if you want to ask me questions in real time, or want to keep to a schedule, or are missing normal human contact and sense of normalcy.^[Please note, as the live lectures are recorded (and posted online), if you join in, **you are consenting to be recorded.** Maryland law requires all parties consent for a conversation or meeting to be recorded.] :)

3. **Office hours** will be held on *Zoom*, at their usual days and times (Monday and Wednesday 3:30-5PM), as described above.

4. We lost a week of classes due to Spring Break, so I will be adjusting and removing certain content on the schedule page to prioritize more important material. I still want to offer you the ability to **suggest topics**, see below. 

5. **Readings, discussions, and discussion grading** will still be out of 5 points, but it will now be evaluated *weekly.* I will still give two lectures per week. I will open up a **Discussion Thread** on **Blackboard** for the week right after my Monday lecture finishes (so around 3 PM).^[To access, go to our course on Blackboard, and on the blue toolbar on the left, go to Discussion Board. There is a test forum and thread that I created that you can feel free to reply to, to make sure everything works for you.] I am interested in your thoughts, reactions, comments, and questions about any of the material (lectures and/or readings). You do not need to write more than a paragraph. Anything more than that, including replying to each others' thoughts, questions, or comments, (which I hope you do!) is solely based on your own interest and curiosity. I will jump in to answer questions the group is stuck on, give my 2 cents, and stir the pot as needed. I hope we still have a conversation and can learn from each other, that was goal always my goal, not to lecture at you! If you crave visual human contact, you can submit your comments/reactions in the form of a short video, and we can try that out!^[Though we might eventually need to move beyond Blackboard in that case. We'll see how things go.] Your participation grade will remain the average out of 5 points for the semester.

Please let me know if you will have difficulty accessing materials or completing assignments at any point this semester. These are special circumstances for everyone. None of us signed up for an online course, and we all have to juggle additional hardships and responsibilities during this chaotic time. I am more concerned for your safety and sanity than your grades, and will be as flexible and generous as I can be.

**The syllabus, including assignments, course format, course content/schedule, and grading, remain subject to change throughout this semester as we experiment.** I will give ample warning and solicit feedback before other major changes.

Lastly, please know that I am wide open to suggestions and feedback! Let me know what is working, and what isn't working for you. This matters more than ever because I am now reaching each of you *individually*, rather than as a *single class together* in person!

# Specific Changes for Current Assignments

Thank you again to those of you who filled out the online survey. It seems most of you are in good shape in terms of accessing materials, and hopefully those of you that left some on campus will have the ability to retrieve them in the coming weeks.

## 1. Midterm Exam 

While as I mentioned before, I've had your midterm ready for you weeks ago, it will not be posted until we return to online classes on March 23. It will be posted on the website with detailed instructions, and you will email me answers by Friday 8:00 PM. It would have been this way even without the switch-to-online courses. Your final will be the same. I will update your grades on Blackboard as I receive them.

## 2. Resuming class

We resume the course on Monday, March 23 with *3.6 - Bureaucracy*. Look on the [<i class="fas fa-info-circle"></i> 3.6 class page](/class/3.6-class) before class begins for a link to the live Zoom stream, and later that day for the videos of the lecture, and other resources. Look also at the [<i class="fas fa-book-reader"></i> 3.6 readings page](/class/3.6-reading) for readings.

## 3. Choosing Topics to Discuss

As promised before the break, I want to allow you to suggest applied topics or current events for us to focus on, which we will then vote on. You can suggest them anonymously [here](https://forms.gle/MEWWwweX7Vu8kEnm6). Please take a few moments to consider what you might be interested in or would like to know more about. You might wonder if it is related to Public Economics, and I assure you no matter what it is, I can probably find a way to relate it to public policy, concepts we've learned, or economics in a relevant and interesting way. Suggestions and actual class lectures in the past have included Blockchain, Net Neutrality, immigration, antitrust, political polarization, the sharing economy, nonprofits, etc. 

> I will give you until **Wednesday March 25 at 2PM**, then I will send out another form for everyone to vote on topics. I will then take the top few topics and try to find a relevant short reading and put together a lecture.

## 4. Your Policy Paper

I have added a [page on the website](/assignment/policy-paper) about your policy paper. I still think having you grapple in writing with a subject using the tools and examples of this course remains an important aspect of the course. The requirements and deadlines remain largely unaffected by this transition, but I may be a bit more lenient on the lengths of these than if we had not had this disruption.