---
title: "Policy Paper Assignment"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

*Due by the last day of class*

<iframe width="560" height="315" src="https://www.youtube.com/embed/W0zli4P6IPM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [<i class="fas fa-chalkboard-teacher"></i> How to Write a Good Paper](/slides/paper-slides.html)
- See examples of good student Op-eds on Blackboard (Course Documents)

> "How can I know what I think until I see what I say?" --- E. M. Forster on Writing


# Overview 

Your task is to write a paper on a public policy or a non-market decision-making process or institution of your choosing, and to apply some economic insights to it. The purpose of this paper is threefold: 

1. to demonstrate to me that you have mastered the material of this course,
2. to develop your writing skills, and
3. to help you develop, change, and/or strengthen your own views by grappling with them in writing.

You may choose to write a paper applying economic analysis to a public policy (a law, a regulatory rule, a government program, etc) that already exists, a public policy that you are proposing to address a social issue, or an analysis of a particular non-market decision-making institution (more on that below)

If you write a paper on a public policy, here are some things to consider:

- What is the stated goal of the policy?
- What are the actual economic consequences of the policy? Intended vs. unintended? Benefits & costs? Which groups benefit and/or are harmed?
- What are the institutions that determine how the collective choice gets made?
- What are the incentives of decision-makers that have led to the particular outcomes? Voters? Politicians? Bureaucrats? Regulators? Interest groups? etc.
- Is this policy robust to knowledge and incentive problems?
- What are the relevant and feasible alternatives to the particular policy chosen? None are perfect, but are any preferable? 

Consider what my colleagues call the Munger test. When you say, "I think the government should do $X$," instead of "government," say "politicians elected by voters should direct bureaucrats to do $X$." Now we see the tradeoffs, incentives, and knowledge issues worth exploring.

The alternative approach to the paper is to write about an interesting non-market decision-making process or institution. The original title of the flagship economic journal *Public Choice*, which publishes articles taking an economic approach to politics, was *Papers on Non-Market Decision-making*. This assignment honors that heritage, that we can use economics to examine many non-market forms of decision-making, politics is just the most frequent alternative. Some obvious examples are charities or private foundations that are neither government agencies nor profit-seeking firms. Some less obvious, but possible more interesting, examples are: competing religious congregations, cults, or other spiritual services; families, households, and marriages; "markets" for love, sex, and marriage; duels and honor cultures; judges, juries, and judicial proceedings; criminal enterprises; open source software; militaries at war, violence, coups, revolution, and repression. The point, again, is that these are institutions that do *not* make individual decisions based on market prices and voluntary exchanges, and often make a single decision binding on everyone. 

I am _NOT_ looking for a survey of existing research, a series of block quotes showing what some economist said about $X$, a regurgitation (or even citations) of my lectures, a list of pros and cons with a last minute conclusion, a book review, and so on. I also do _NOT_ want you to compress *everything* you learned from this class into a single paper. You should only use those insights that are *relevant* to your topic and your argument (it may only be one or two things!). 

The titles (and topics) of previous papers written for this class include:

- "The Formation of Super PACs"
- "The Industrial Organization of Terrorist Groups"
- "Capital Punishment"
- "The Economics of Cults"
- "Trump's Steel and Aluminum Tariffs"
- "Bigger Wall, Bigger Social Cost"
- "Limiting the Power of Public Opinion"
- "An Examination of the Iran Deal"
- "The Basic Income Guarantee Will Do What for the Economy?"
- "Donald Trump’s Tax Cuts and Jobs Act"
- "The Economics of Net Neutrality"

Please note that, while you are not required to, I highly recommend discussing your ideas with me over email or in person. I will also read any drafts you would like to submit to me early, and provide you with helpful comments, subject to my own availability.

**This paper is due by email the date and time of our final exam period, and is 30% of your course grade.**

# Length, References, & Mechanics

The goal of any op-ed is to convince reasonably-educated readers of some particular conclusion (also known as a *thesis*). This conclusion is of course, the opinion of the author, but this opinion must be backed by theory and evidence that leads reasonable people to agree with that conclusion. The claim you make as your conclusion should be relevant, debatable, testable, and provide new insight on a topic. Telling the reader *"people who do not recycle are selfish"* is neither informative nor persuasive, but telling the reader *"recycling reduces the amount of trash going into local landfills by X tons a year"* is at least informative, if not also persuasive. **You are free to take any position on any issue that you choose, so long as it is backed by evidence and sound use of the economic way of thinking.** For more details, see my presentation slides linked above. 

I always hesitate to give formal length requirements, because most students will write the bare minimum, and also because different papers have different optimal lengths. What truly matters is that your paper is long enough to say what you need to say, to say it well, and to say it briefly. Ceterus paribus, if papers A and B say the same thing, but paper B says it in half the length (without sacrificing key arguments), paper B is a better paper. 

Since you of course still want to know what a good length will be, my rule of thumb is that your paper should be about **10 $\pm$ 5 pages** (size 12 font, double spaced, 1" margins). This will depend on the topic you have chosen to written on, and your own personal writing style. There are no other formal requirements but, I recommend formatting it in 12 point Times New Roman or Arial font, double spaced, just to make it easier for me to read (and nearly every other paper you write will ask for this).

I would also like you to use scholarly references, that is, articles from economics journals and cite them properly. I do not have a minimum requirement of the amount of references, but I expect you to have at least **2-5 scholarly references**, depending on your paper topic and thesis.^[Our course readings might even cover you for a few here, depending on the topic!] I am not particularly picky about exactly how you format your citations or bibliography, just please be consistent, and do not use footnotes or endnotes (only because they annoy me). I *suggest* the APA author-year-page in-text citation format that is fairly standard in economics journals, i.e.: "The division of labor is limited by the extent of the market," (Smith 1776: 27). Look at my slides or any of our readings for a suggested bibliography style.

# Sources for Inspiration

Here is a list of a few places you might consider to dig up some information on your topic, or to help you find a topic. Just be sure to read and cite the actual sources that these secondary sources cite. 

- Major news outlets (e.g. CNN, Wall Street Journal, New York Times, USA Today, Huffington Post, the Guardian) and wherever you may find your news (e.g. reddit, Buzzfeed, etc) both for current events, and also their Opinion/Commentary sections for other op-eds to learn from and/or critique
- Wikipedia -- no seriously, it is the first place I go to learn about a new topic. Just be sure to actually investigate the underlying research and use that for your references!
- Economics Podcasts
    - [Econtalk](http://econtalk.org) -- a fantastic podcast series by Russ Roberts that interviews famous economists, philosophers, businesspeople, and other figures who have an impact on the world of ideas	
    - [Freakonomics (Radio)](http://freakonomics.com/) -- another great podcast by one of the authors of the famed *Freakonomics* books about intermediate-level economic topics, often an in-depth series of interviews on a major issue 
    - [NPR Planet Money](http://npr.org/sections/money) -- another good podcast series on economics topics and current events, much shorter and more 10,000-foot level approach than Econtalk or Freakonomics
- Popular Economists' Blogs/Blogs on Economics:
    - [Marginal Revolution](http://marginalrevolution.com) -- Tyler Cowen & Alex Tabarrok (head and shoulders above the rest!)
    - [Cafe Hayek](http://cafehayek.org) -- Don Boudreaux (libertarian-leaning, mostly just Don on trade and micro-policy)
    - [EconLog](http://econlog.org) -- Bryan Caplan, David Henderson (libertarian-leaning, good analysis)
    - [The Conscience of a Liberal](http://krugman.blogs.nytimes.com/) -- Paul Krugman at New York Times (strong left-wing politics)
    - [The Grumpy Economist](https://johnhcochrane.blogspot.com/) -- John Cochrane (Chicago School approach)
    - [Greg Mankiw's Blog](http://gregmankiw.blogspot.com) -- Greg Mankiw (moderate conservative, New Keynesian approach)
    - [Undercover Economist](http://timharford.com/articles/undercovereconomist/) -- Tim Harford (British, non-political, very easy to understand)
    - [Chris Blattman](https://chrisblattman.com/) -- Chris Blattman (great on economic development, poverty, and conflict in poor countries)
    - [Slate Star Codex](http://slatestarcodex.com) -- "Scott Alexander" (a pseudonym, apparently a Medical Student, but one of the most lucid social science blogs ever written)
    - [Fivethirtyeight](https://fivethirtyeight.com/) -- Nate Silver & co. (a journalist, but a *leader* on using data and statistics in social science and journalism)
    - [Andrew Gelman](http://andrewgelman.com) -- Andrew Gelman (a statistician, but another *leader* on using data and statistics for social science)

# Grading Rubric and Deadlines

Here is the rubric that I will use to grade your paper:

| Category | Points |
|----------|-------:|
| Persuasiveness | 25 |
| Soundness | 25 |
| Clarity | 25 |
| Organization | 10 |
| References | 10 |
| Style | 5 |
| TOTAL | 100 |

- **Persuasiveness:** How persuasive is your argument? Would a reasonably educated college-level reader who is familiar with economics but not necessarily this course find themselves understanding your argument and agreeing with you? (Write for an audience wider than just members of this class. Therefore, don't use terms, sources, or "inside jokes" that only other students in this class (and no one else) would understand.) Remember, your goal is not to convince *me* (though you may), your goal is to convince _someone else_, and I grade you the probability that this is likely. You are the lawyer, I am the judge, and your audience is the jury.
- **Soundness:** Are your theories consistent and logical, and did you apply them correctly? Did you choose relevant (and non-cherry picked) evidence to back it up? Are your facts, data, or case studies accurate?
- **Clarity**: How clear is your paper? Is it clear what your thesis is and is it declared early on? Can you summarize the thesis in a sentence? Are there confusing passages, excessive jargon or passive voice, or irrelevant arguments and examples?
- **Organization**: Is your paper organized? Have you presented your separate arguments/examples in a logical order? Is it clear when you are moving on from one section to another? Is it clear when and where you are summarizing and concluding?
- **References**: Does your paper use multiple scholarly references? Does it properly cite them in the text for main ideas borrowed and for direct quotations? Are they consistently listed at the end in a references section?
- **Style**: Is your paper interesting and easy to read? Does it engage the reader? Is it written in active voice? This is somewhat subjective, and hence, the smallest portion of your grade.

# Other Resources

You all have, or have had me, for ECON 306, and have all had "the talk" about writing a good paper from me when you wrote the Op-ed for that class. I was absent this semester when I would give "the talk" to my ECON 306 class, so fortunately for you all, you can find it in video form, along with the slides, to help you write a good paper (skip to 17:30, the first bit is about the Op-ed): [ECON 306: Op-Ed Assignment](https://micros20.classes.ryansafner.com/assignment/op-ed/) 